services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin           # Nome do usuário
      POSTGRES_PASSWORD: admin       # Senha do banco
      POSTGRES_DB: laravel_empresas_database  # Nome do banco de dados
    ports:
      - "5432:5432"                  # Porta do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: